name: HSI_Denoising_FastHyDe
algorithm_name: FastHyDe
denoiser_name: BM3D
manual_seed: 1004
p_subspace: 10

# dataset settings
datasets:
  scene_name: pavia #WashingtonDC, pavia
  HSI_dir: ../Datasets/
  noise_case: case1
  noise_level: 0.1 #0.1, 0.08, 0.06, 0.04, 0.02

# save and show
save_result: True
save_dir: ./Results/
paper_fig_save_dir: ../Results
paper_metric_save_dir: ../Results/metrics.csv
log_file_name: log.txt
plt_figure: True
band_show: 50
selected_bands: [49, 27, 7]
show_figure: False
save_figure: True

